### ISSUE TITLE
Need to Verify Links/Blue & Red Boxes

### ISSUE THREAD

**Issue by ediedrich** [OP5-Employee/OP5-Documentation#25]
Some of the links seem to be random. Need to double check that all of these are necessary and correct.

- [x] 14.6, pg. 57 “Parenting.”- random link
- [x] 14.6.2.1, pg. 58 “Hosts and services”- random link
- [x] 18.3.2.1, pg. 70 - Incorrect URL link
- [x] 20.3, pg. 84 “Graph Template documentation” - random link
- [x] 22, pg. 94 “Event’s and logs” and “Reports”  - random links
- [x] 23.2.3.1, pg. 97, “Creating a Top alert producers report”  - links to the last page - for no reason?
- [x] 23.2.4.1, pg. 97, “Creating a Top alert producers report”  - links to the last page - for no reason?
- [x] 23.2.4.1, pg. 97, “Schedule reports” - random link
- [x] 24.2.3.1, pg. 107, Creating SLA report, links to the last page - for no reason?
- [x] 24.3.3.1, pg. 114, "Creating an availability report", links to the last page - for no reason?
- [x] 24.5, pg. 115, "Creating SLA report" "availability report" "save reports" - links to the last page - for no reason?
- [x] 24.5.1, pg. 115, "Creating SLA report" "save reports", links to the last page - for no reason?
- [x] 24.5.2, pg. 116, "Creating SLA report" links to the last page - for no reason?
- [x] 26.6, pg. 120, CORRECT URL LINK
- [x] 26.7.1, pg. 120 "services" random link - probably not needed
- [x] 26.7.2, pg. 121  "services" random link - probably not needed
- [x] 26.7.3, pg. 121  "services" random link - probably not needed
- [x] 26.7.4, pg. 122  "syslog" random link - probably not needed
- [x] 27.1, pg. 125 " Filters" Random Link
- [x] 27.1, pg. 125 " Listview filter columns" CORRECT URL LINK
- [x] 27.3, pg. 130 CORRECT URL LINK
- [x] 27.3, pg. 131 " Listview filter columns" CORRECT URL LINK
- [x] 28.1, pg. 131, "Filters" random link
- [x] 28.2, pg. 131 " Listview" "Filter" random link
- [x] 28.2.2, pg. 132 "Listviews" random link
- [x] 30.2.1, pg. 137 Broken URL link
- [x] 31.1, pg. 141, "Authorization" random link
- [x] 33.6.2, pg. 148 "Filters" random link
- [x] 34.3, pg. 151 "widgets" random link
- [x] 34.5, pg. 156 "Authorization section" random link
- [x] 35.1, pg. 157 "dashboard" random link
- [x] 36.1.1, pg. 163-164 All links in this section work except for the Windows: "NSClient++" link
- [x] 37.1, pg. 164 CORRECT URL LINK
- [x] 37.2, pg. 165 CORRECT URL LINK
- [x] 37.6, pg. 166 "the command defined earlier"  links to the last page - for no reason?
- [x] 38.1, pg. 166  CORRECT URL LINK
- [x] 38.1, pg. 167  CORRECT URL LINK
- [x] 38.3.1, pg. 167, CORRECT URL LINKS
- [x] 38.3.2, pg. 167, "our more in-depth material from our knowledge Article" links to an internal KB document instead of external facing
- [x] 39.2, pg. 169 CORRECT URL LINK
- [x] 39.2, pg. 170 links to the last page - for no reason?
- [x] 41.1, pg. 175, "API help page" CORRECT URL LINK
- [x] 41.1, pg. 175, invalid url link below
- [x] 41.2, pg. 175, "Filters"  random link
- [x] 41.2.2, pg. 175, "hosts"  links to host page - probably don't need
- [x] 41.2.2, pg. 175, "here" CORRECT URL LINK
- [x] 41.3, pg. 175, "here" CORRECT URL LINK
- [x] 41.4, pg. 176, "here" CORRECT URL LINK
- [x] 41.7, pg. 176, incorrect url link
- [x] 41.7, pg. 177, incorrect url link
- [x] 42.1, pg. 178 all four links are broken
- [x] 46.6, pg. 187, CORRECT URL LINKS
- [x] 50.3.1.1, pg. 190, "Plugins included in OP5 Monitor" "Developing your own check plugin" "OP5 on Naemon, Nagios and the future" Broken url links
- [x] 50.3.1.1, pg. 190, "installing third-party plugins" "The Naemon project website" CORRECT URL LINK
- [x] 50.3.2.1, pg. 190, all broken links
- [x] 50.3.3.1, pg. 190, "Livestatus community space" broken link
- [x] 50.3.3.1, pg. 190, "Documentation for the original version of MK Livestatus" CORRECT URL LINK
- [x] 50.3.4.4, pg. 191" Logger documentation" "Monitoring log files in Monitor 7.0 or higher" "Documentation for syslog-ng OSE" all broken links
- [x] 50.3.4.4, pg. 191 "Using Logger and custom columns for root cause analysis" CORRECT URL LINK
- [x] 50.3.5.1, 50.6.1, pg. 191 "Trapper documentation" broken link
- [x] 50.3.5.1, 50.6.1, pg. 191 "Getting started with OP5 Trapper" "Manual page for snmptrapd configuration (external) CORRECT URL LINK
- [x] 50.6.1, pg. 191 "Business Services documentation" "Business Service monitoring manual" "Introduction to Business Services Management in OP5 Monitor" all broken links
- [x] 50.6.1, pg. 191 "4 steps to turn on simple BSM in your system" CORRECT URL LINK
- [x] 50.3.7.1, pg. 192 broken link
- [x] 50.3.8.1, pg. 192 broken link
- [x] 50.3.9, pg. 192 CORRECT URL LINK
- [x] 50.3.9.1, pg. 192 "HTTP API documentation" broken link
- [x] 50.3.9.1, pg. 192 "Submitting status updates through the HTTP API"  CORRECT URL LINK
- [x] 51.2.1, pg. 193 broken link
- [x] 58.4.2, pg. 208 broken link
- [x] 59.4, pg. 212 links to the last page - for no reason?
- [x] 59.9, pg. 218 CORRECT URL LINKS
- [x] 63.5.5, pg. 246 links to the last page - for no reason?
- [x] 67.2, pg. 273 CORRECT URL LINK
- [x] 70.1, pg. 275 CORRECT URL LINK
- [x] 71.1, pg. 277 CORRECT URL LINK
- [x] 78.1, pg. 284 CORRECT URL LINK
- [x] 79.1, pg. 284 broken link
- [x] 80, pg. 284 "agent download page" broken link
- [x] 80, pg. 284 "manual for Windows Syslog Agent" CORRECT URL LINK
- [x] 81.3, pg. 286  CORRECT URL LINK
- [x] 83.2, pg. 286  CORRECT URL LINKS
- [x] 83.5, pg. 288 CORRECT URL LINKS
- [x] 83.7, pg. 290 CORRECT URL LINKS
- [x] 86.1, pg. 294 CORRECT URL LINKS
- [x] 86.2, pg. 296 CORRECT URL LINKS
- [x] 87.1, pg. 296 "plugin interface" broken link
- [x] 87.1, pg. 296 "PuTTY" "WinSCP" CORRECT URL LINKS
- [x] 88.1, pg. 297 broken link
- [x] 88.3 pg. 299 CORRECT URL LINKS
- [x] 89.1, pg. 299 "mentioned that Naemon maintains plugin compatibility with Nagios" links to internal KB article rather than external
- [x] 89.1, pg. 299 "the macro list" "a great page for understanding how to think about them" CORRECT URL LINKS
- [x] 93.1.2, pg. 305 broken link
- [x] 93.2.1.1, pg. 305 one broken link and one links to the bottom of the document
- [x] 93.2.2.1, pg. 307 one broken link and two links to the bottom of the document
- [x] 93.2.4, pg. 307 broken link
- [x] 93.2.5, pg. 308 broken link
- [x] 93.3, pg. 308 CORRECT URL LINKS
- [x] 94.2.1, pg. 310 broken link
- [x] 94.2.2, pg. 310 broken link
- [x] 94.3.1.1, pg. 310 links to the bottom of the document
- [x] 94.3.2.1, pg. 311 links to the bottom of the document
- [x] 94.3.4, pg. 312 broken links
- [x] 94.4, pg. 312 CORRECT URL LINKS
- [x] 95.2, pg. 312 broken links
- [x] 95.4, pg. 314 broken link
- [x] 97.2.9.1, pg. 320 CORRECT URL LINK
- [x] 97.2.9.1, pg. 320 weird strikeout
- [x] 100.1, pg. 328 CORRECT URL LINKS
- [x] 101.1, pg. 328 CORRECT URL LINK
- [x] 101.2, pg. 328 CORRECT URL LINK
- [x] 102.1, pg. 329 CORRECT URL LINK
- [x] 102.2, pg. 329 Does not take you to download library
- [x] 106.4, pg. 338 broken link
- [x] 106.6.1, pg. 342 CORRECT URL LINK
- [x] 106.8, pg. 344 CORRECT URL LINK

**Comment by ediedrich** [comment]
Updated @jollyrogue with more specific information.

**Comment by jollyrogue** [comment]
00-02-08c-NagVis_maps.md fixed on 7-31.

* 18.3.2.1, pg. 70 - Incorrect URL link

**Comment by jollyrogue** [comment]
00-02-09-Viewing_Graphs.md fixed on 7-31. 

* 20.3, pg. 84 “Graph Template documentation” - random link

Also fixed table roadkill. It's now a table again, with most of it's parts in the correct places. :)

**Comment by jollyrogue** [comment]
00-03-01-Events_and_logs.md fixed on 7-31

- 23.2.3.1, pg. 97, “Creating a Top alert producers report” - links to the last page - for no reason?
- 23.2.4.1, pg. 97, “Creating a Top alert producers report” - links to the last page - for no reason?
- 23.2.4.1, pg. 97, “Schedule reports” - random link

**Comment by jollyrogue** [comment]
00-03-02-Reports.md fixed on 8-1.

- 24.2.3.1, pg. 107, Creating SLA report, links to the last page - for no reason?
- 24.3.3.1, pg. 114, "Creating an availability report", links to the last page - for no reason?
- 24.5, pg. 115, "Creating SLA report" "availability report" "save reports" - links to the last page - for no reason?
- 24.5.1, pg. 115, "Creating SLA report" "save reports", links to the last page - for no reason?
- 24.5.2, pg. 116, "Creating SLA report" links to the last page - for no reason?

**Comment by jollyrogue** [comment]
Note: `:%s/\[\([a-zA-Z ]\+\)\]([a-zA-Z0-9#-]\+)/\1/gc` to find and replace links with just the text.

**Comment by jollyrogue** [comment]
00-04-01-Filters.md fixed on 8-1.

- 26.7.1, pg. 120 "services" random link - probably not needed
- 26.7.2, pg. 121 "services" random link - probably not needed
- 26.7.3, pg. 121 "services" random link - probably not needed
- 26.7.4, pg. 122 "syslog" random link - probably not needed

**Comment by jollyrogue** [comment]
00-04-05-Navigation.md fixed as of 8-1.

- 30.2.1, pg. 137 Broken URL link

This should have been an code example which was incorrectly interpreted.

**Comment by jollyrogue** [comment]
00-04-06-Quick-Action-Menu.md fixed as of 8-1.

- 31.1, pg. 141, "Authorization" random link

**Comment by jollyrogue** [comment]
00-04-08-Searching.md fixed as of 8-1.

-  33.6.2, pg. 148 "Filters" random link

**Comment by jollyrogue** [comment]
01-12-02-Load_balanced_monitoring.md should be fixed as of 8-6.

- 94.2.1, pg. 310 broken link
- 94.2.2, pg. 310 broken link
- 94.3.1.1, pg. 310 links to the bottom of the document
- 94.3.2.1, pg. 311 links to the bottom of the document
- 94.3.4, pg. 312 broken links

**Comment by jollyrogue** [comment]
01-12-01-Distributed_Monitoring.md should be fixed as of 8-6.

- 93.1.2, pg. 305 broken link
- 93.2.1.1, pg. 305 one broken link and one links to the bottom of the document
- 93.2.2.1, pg. 307 one broken link and two links to the bottom of the document
- 93.2.4, pg. 307 broken link
- 93.2.5, pg. 308 broken link

**Comment by jollyrogue** [comment]
Should be fixed as of 8-7.

- 41.7, pg. 176, incorrect url link
- 41.7, pg. 177, incorrect url link

**Comment by jollyrogue** [comment]
Strikeout should be removed as of 8-7.

- 97.2.9.1, pg. 320 weird strikeout
