### ISSUE TITLE
Text separated due to picture formatting

### ISSUE THREAD

**Issue by ediedrich** [OP5-Employee/OP5-Documentation#29]
Some of the text is awkwardly split between to lines due to its interaction with a picture near by.

- [x] Section 20.4, pg. 88 "After"
- [x] 24.3.3.1, pg. 114 "Click port."
- [x] 26.2, pg. 117
- [x] 27.2, pg. 125
- [x] 30.6, pg. 138 " hover the"
- [x] 42.1, pg. 177 "We store"
- [x] 43.3, pg. 178-179 "different parts"
- [x] 60.2.1, pg. 216
- [x] 61.2.3, pg. 219 "Lookup button"
- [x] 61.2.3, pg. 219-220 "an X"
- [x] 61.2.4, pg. 220-221 "group called"
- [x] 63.3.1.1, pg. 229 "the changes"
- [x] 63.4.8, pg. 235
- [x] 63.5.1.1, pg. 236 "The add"
- [x] 63.5.2.1, pg. 237 "Advanced"
- [x] 63.7.1, pg. 244 "automatically"
- [x] 64.2, pg. 252 "This will open"
- [x] 64.2, pg. 253-254 "Add More Hosts"
- [x] 65.4.1, pg. 257-258 "propagate"
- [x] 65.5. pg. 259 "Select a"
- [x] 70.2, pg. 264 "note on"
- [x] 75.2, pg. 270 "modify, then"
- [x] 81.2.2, pg. 272 "Archive logs"
- [x] 83.7, pg. 276-277 "Example:"
- [x] 93.1, pg. 290 " looks like"
- [x] 104.2, 3., pg. 318 "below images"
- [x] 106.4, 1., pg. 324 "replacing"("

**Comment by KenDobbins** [comment]
This SHOULD be resolved by Pull request #34 

@ediedrich Can you confirm that that a spot check of the files now meet the expected standard

**Comment by ediedrich** [comment]
Does this one need to be closed/can I help? @jollyrogue

**Comment by jollyrogue** [comment]
@ediedrich We believe these have been fixed. If you could check off the pictures which are fixed it would be helpful.

**Comment by ediedrich** [comment]
Checked - all fixed.
