### ISSUE TITLE
Reports page looking nasty because of block text

### ISSUE THREAD

**Issue by joncav** [OP5-Employee/OP5-Documentation#48]
00-03-02-Reports_md.pdf
On nearly every page there is text that is formatted to be block text. This is messing up how it displays in pdf and is running over the margin and off the page. Ryan has the fix for this.

**Comment by jollyrogue** [comment]
Check tomorrow's PDFs as I'm not seeing the issue when I generate the PDF.

**Comment by ediedrich** [comment]
Fixed
