### ISSUE TITLE
LDAP - blank page possibly from break, and block text issue

### ISSUE THREAD

**Issue by joncav** [OP5-Employee/OP5-Documentation#51]
01-02-04-LDAP_and_Actrive_Directory_md.pdf
There is a random blank page here probably due to the enter/page breaks we added in from the script. There is also the block text issue on the last page.

**Comment by jollyrogue** [comment]
The screenshot is too big to fit on a page with any text. I moved some text around, and now it's on it's own page.
Will be fixed in next PDF release.

**Comment by ediedrich** [comment]
Fixed
