### ISSUE TITLE
User Menus - block text

### ISSUE THREAD

**Issue by joncav** [OP5-Employee/OP5-Documentation#61]
01-15-00-User_Menus_md.pdf
long skinny table issue

**Comment by dblando** [comment]
I reviewed the [source page for User Menus](https://kb.op5.com/display/DOC/User+Menus). The original tables obscure the solution.

It looks like those tables could be turned into subsections about the Main Page meanings, then separate ones for BSM, Host, and Service. This would save a lot of wasted columns.

**Comment by dblando** [comment]
Replaced table with h4 & h5 subsections and list items.

**Comment by dblando** [comment]
Reviewed with Ryan. Apologies for not branching from proofing_wip to do the work.
